when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

#  framework:
#     session:
#         # ...
#         handler_id: 'session.handler.native_file'
#         save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
#         # improves the security of the cookies used for sessions
#         cookie_secure: auto
#         cookie_samesite: lax
#         storage_factory_id: session.storage.factory.native